gitlab:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: 'gitlab.gateray.org'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://gitlab.gateray.org:9090'
      gitlab_rails['gitlab_shell_ssh_port'] = 22
  ports:
    - '9090:9090'
    - '2224:22'
  volumes:
    - '/data/gitlab/config:/etc/gitlab'
    - '/data/gitlab/logs:/var/log/gitlab'
    - '/data/gitlab/data:/var/opt/gitlab'
