master:
  image: 'jenkins'
  restart: always
  hostname: 'jenkins.gateray.org'
  environment:
    JAVA_OPTS: "-Djava.awt.headless=true"
  ports:
    - "50000:50000"
    - "8080:8080"
  volumes:
    - /data/jenkins_home:/var/jenkins_home
